(function () {
  const translations = {
    'pt-BR': {
      'meta.description': 'Monitor público de acontecimentos, clima, atividade sísmica, auroras e condições globais em tempo quase real.',
      'system.online': 'SISTEMA ONLINE', 'system.partial': 'DADOS PARCIAIS', 'system.offline': 'SEM FONTES', 'system.responding': 'FONTES RESPONDENDO', 'system.syncing': 'SINCRONIZANDO', 'system.sync': 'SINCRONIA {time}',
      'theme.light': 'MODO CLARO', 'theme.dark': 'MODO ESCURO',
      'nav.about': 'SOBRE', 'manifest.eyebrow': 'MONITOR GLOBAL / AO VIVO', 'manifest.line1': 'O PLANETA', 'manifest.line2': 'NÃO PAUSA.', 'manifest.description': 'Ocorrências públicas reunidas em uma leitura única, com origem, horário e localização verificáveis.',
      'risk.title': 'FILTRO DE RISCO', 'risk.highOnly': 'Somente alta prioridade', 'layers.title': 'CAMADAS OPERACIONAIS', 'layers.temperature': 'Temperatura global', 'layers.aurora': 'Auroras norte e sul', 'layers.air': 'Qualidade do ar', 'layers.regions': 'Notícias por estado / província', 'layers.conflicts': 'Conflitos na imprensa', 'layers.daylight': 'Linha dia / noite', 'layers.satellite': 'Satélite NASA diário', 'layers.iss': 'Posição da ISS',
      'sources.title': 'INTEGRIDADE DAS FONTES', 'sources.loading': 'Consultando fontes públicas…', 'sources.fail': 'FALHA', 'sources.ok': '{count} · OK', 'sources.snapshot15': 'Snapshot renovado a cada 15 min', 'sources.activeOnly': 'Somente alertas ativos', 'sources.grid15': 'Grade global de 15°', 'sources.newsCache': 'Cache público renovado a cada 15 min', 'sources.conflictMedia': 'Monitoramento jornalístico renovado a cada 15 min', 'sources.published': 'publicado', 'sources.checked': 'consultado', 'sources.stale': 'ATRASADO',
      'stage.eyebrow': 'VISÃO ORBITAL / DADOS PÚBLICOS', 'stage.visible': 'OCORRÊNCIAS VISÍVEIS', 'stage.locate': '⌖ PERTO DE MIM', 'stage.regions': 'NOTÍCIAS', 'stage.hideRegions': 'OCULTAR NOTÍCIAS', 'stage.map2d': 'MAPA 2D', 'stage.globe3d': 'GLOBO 3D', 'stage.refresh': '↻ ATUALIZAR', 'stage.loading': 'INICIALIZANDO CARTOGRAFIA', 'stage.unavailable': 'CARTOGRAFIA INDISPONÍVEL',
      'legend.critical': 'Crítico', 'legend.high': 'Alto', 'legend.medium': 'Médio', 'legend.low': 'Baixo',
      'status.temperatureOff': 'TEMPERATURA: DESATIVADA', 'status.auroraOff': 'AURORA: DESATIVADA', 'status.airOff': 'AR: DESATIVADO', 'status.regionsOff': 'NOTÍCIAS REGIONAIS: DESATIVADAS', 'status.conflictsOff': 'CONFLITOS NA IMPRENSA: DESATIVADOS', 'status.satelliteOff': 'SATÉLITE: DESATIVADO', 'status.issWaiting': 'ISS: AGUARDANDO',
      'spot.waiting': 'AGUARDANDO', 'spot.eyebrow': 'EM DESTAQUE', 'spot.consulting': 'CONSULTANDO FONTES', 'spot.initial': 'Os dados reais aparecerão quando as fontes responderem.', 'spot.indicator': 'INDICADOR PRINCIPAL', 'spot.source': 'FONTE', 'spot.updated': 'ATUALIZAÇÃO', 'spot.coordinates': 'COORDENADAS', 'spot.open': 'ABRIR FONTE ↗',
      'space.eyebrow': 'CLIMA ESPACIAL / NOAA', 'space.title': 'MAGNETISMO DA TERRA', 'space.wind': 'VENTO SOLAR', 'space.waiting': 'Aguardando NOAA SWPC.', 'feed.eyebrow': 'PULSO GLOBAL', 'feed.title': 'ÚLTIMAS LEITURAS',
      'intel.eyebrow': 'INTELIGÊNCIA REGIONAL', 'intel.title': 'NOTÍCIAS E CÂMERAS', 'intel.placeholder': 'Estado, província ou país', 'intel.search': 'BUSCAR', 'intel.initial': 'Selecione um evento ou pesquise uma região.', 'intel.cameras': 'BUSCAR CÂMERAS EXTERNAS NO WINDY ↗', 'intel.notifications': 'ATIVAR ALERTAS NO NAVEGADOR', 'intel.disclaimer': 'Notícias não são confirmação independente. O botão de câmeras abre um serviço externo; disponibilidade, proximidade e atualização não são garantidas.',
      'footer.monitor': 'MONITOR INDEPENDENTE · DADOS PÚBLICOS', 'footer.sync': 'ÚLTIMA SINCRONIA —',
      'about.eyebrow': 'SOBRE ESTE MONITOR', 'about.title': 'Informação global, com fonte e contexto.', 'about.lead': 'Seu Mundo Neste Momento reúne dados públicos sobre acontecimentos naturais, condições ambientais, clima espacial e atividade humana em uma única visualização. O objetivo é facilitar o acesso à informação, não provocar medo nem antecipar conclusões.',
      'about.realtimeTitle': 'O que significa “tempo quase real”', 'about.realtime': 'Cada instituição publica em um ritmo diferente. A posição da ISS pode mudar em segundos; terremotos, alertas, auroras, clima e imagens de satélite podem levar de minutos a horas. O horário exibido pertence à leitura mais recente disponibilizada pela fonte — não necessariamente ao instante exato em que o fato começou.',
      'about.dataTitle': 'Como os dados são tratados', 'about.data': 'O painel informa fonte, horário e localização sempre que esses dados existem. A camada térmica representa a temperatura do ar a 2 metros estimada pelo modelo NOAA GFS; a superfície colorida é interpolada entre células do modelo, não entre termômetros. Se uma fonte falhar, o sistema sinaliza a indisponibilidade ou utiliza o último snapshot identificado como contingência. Valores ausentes não são preenchidos por estimativas inventadas.', 'about.limitsTitle': 'Limites importantes',
      'about.limit1': 'Este projeto não substitui autoridades, defesa civil, serviços meteorológicos ou atendimento de emergência.', 'about.limit2': 'Notícias são referências jornalísticas e não confirmação independente.', 'about.limit3': 'Câmeras públicas podem ter atraso, sair do ar ou não mostrar o local exato.', 'about.limit4': 'Alertas nucleares, radiológicos, biológicos ou químicos só podem aparecer após publicação de uma fonte oficial previamente aceita.', 'about.limit5': 'O monitor não calcula trajetórias de armamentos, não prevê impactos e não atribui responsabilidade sem confirmação oficial.',
      'about.note': 'Projeto independente, sem vínculo institucional com as fontes consultadas. O Google Analytics é usado somente após consentimento para contar visitas e usuários ativos. Conteúdo externo pode permanecer no idioma original para preservar a informação publicada.', 'about.signature': 'CONCEITO, DIREÇÃO VISUAL E DESENVOLVIMENTO',
      'consent.text': 'Este site usa medição anônima do Google Analytics para contar visitas e usuários ativos.', 'consent.allow': 'PERMITIR', 'consent.reject': 'RECUSAR',
      'cat.all': 'Todos', 'cat.earthquakes': 'Terremotos', 'cat.wildfires': 'Incêndios', 'cat.storms': 'Tempestades', 'cat.volcanoes': 'Vulcões', 'cat.floods': 'Inundações', 'cat.other': 'Outros', 'cat.hazmat': 'Biológico / químico', 'cat.nuclear': 'Nuclear / radiológico',
      'risk.critical': 'NÍVEL CRÍTICO', 'risk.high': 'NÍVEL ALTO', 'risk.medium': 'NÍVEL MÉDIO', 'risk.low': 'NÍVEL BAIXO',
      'event.quake': 'Terremoto {magnitude}', 'event.wildfire': 'Incêndio ativo', 'event.storm': 'Tempestade monitorada', 'event.volcano': 'Atividade vulcânica', 'event.flood': 'Inundação ativa', 'event.other': 'Evento natural', 'event.gdacsWildfire': 'Incêndio monitorado pelo GDACS', 'event.gdacsFlood': 'Inundação monitorada pelo GDACS', 'event.gdacsStorm': 'Ciclone tropical monitorado', 'event.gdacsVolcano': 'Atividade vulcânica monitorada', 'event.gdacsOther': 'Desastre monitorado pelo GDACS', 'event.tsunami': 'Alerta oficial de tsunami', 'event.unknownLocation': 'Local não informado', 'event.quakeSummary': 'Evento sísmico publicado pelo USGS. Profundidade aproximada de {depth} km.', 'event.eonetSummary': 'Evento aberto acompanhado pelo NASA EONET.', 'event.active': 'ATIVO', 'event.none': 'Nenhuma ocorrência corresponde aos filtros.',
      'kp.none': 'Sem tempestade', 'kp.minor': 'Menor', 'kp.moderate': 'Moderada', 'kp.strong': 'Forte', 'kp.severe': 'Severa', 'kp.extreme': 'Extrema', 'space.latest': 'Leitura mais recente: {time}. Bz negativo favorece o acoplamento com o campo terrestre.',
      'layer.tempLoading': 'TEMPERATURA: CARREGANDO CAMPO GLOBAL', 'layer.tempUnavailable': 'TEMPERATURA: MODELO GFS INDISPONÍVEL', 'layer.tempNoReading': 'TEMPERATURA: SEM LEITURA', 'layer.tempPoints': 'TEMPERATURA: {count} PONTOS · {min} A {max} °C', 'layer.tempField': 'TEMPERATURA: NOAA GFS · {time} · {min} A {max} °C', 'layer.auroraCells': 'AURORA: {count} CÉLULAS NOAA', 'layer.airPoints': 'AR: {count} PONTOS · GRADE 15°', 'layer.airUnavailable': 'AR: SNAPSHOT INDISPONÍVEL', 'layer.regionsLoading': 'NOTÍCIAS: VERIFICANDO COBERTURA REGIONAL', 'layer.regionsCount': 'NOTÍCIAS: {count} ESTADOS / PROVÍNCIAS COBERTOS', 'layer.regionsUnavailable': 'NOTÍCIAS: BASE REGIONAL INDISPONÍVEL', 'layer.regionSelected': 'NOTÍCIAS: {name}', 'layer.conflictsLoading': 'CONFLITOS: VERIFICANDO COBERTURA', 'layer.conflictsCount': 'CONFLITOS NA IMPRENSA: {count} REFERÊNCIAS', 'layer.conflictsEmpty': 'CONFLITOS: SEM REFERÊNCIAS REGIONAIS NO IDIOMA', 'layer.satelliteOn': 'SATÉLITE: NASA GIBS · {date} · DIÁRIO',
      'iss.snapshot': 'ISS: SNAPSHOT DE CONTINGÊNCIA', 'iss.unavailable': 'ISS: FONTE INDISPONÍVEL', 'weather.loading': 'Consultando Open-Meteo…', 'weather.feels': 'Sensação', 'weather.humidity': 'Umidade', 'weather.wind': 'Vento', 'weather.unavailable': 'Clima indisponível: {error}',
      'news.loading': 'Verificando notícias públicas…', 'news.coverage': 'Somente notícias no idioma selecionado, das últimas 24 horas e com cobertura regional identificável. Cache renovado a cada 15 minutos.', 'news.fallback': 'Cobertura regional insuficiente; exibindo o país.', 'news.none': 'Nenhuma notícia correspondente foi encontrada no cache recente para “{term}”.', 'news.source': 'Fonte jornalística', 'news.noTime': 'horário não informado', 'news.error': 'O cache público de notícias está temporariamente indisponível.', 'news.google': 'Pesquisar no Google Notícias ↗', 'news.preview': 'PRÉVIA DA NOTÍCIA', 'news.originalNotice': 'A manchete e os metadados abaixo foram publicados pela fonte indicada. O conteúdo completo permanece no site de origem.', 'news.read': 'LER NOTÍCIA COMPLETA ↗',
      'region.click': '{country} · clique para notícias', 'region.metric': 'REGIÃO', 'region.newsMetric': 'NOTÍCIA RECENTE', 'temperature.approx': 'Temperatura aproximada', 'temperature.legend': 'TEMPERATURA DO AR A 2 M · MODELO GFS', 'temperature.readout': '{value} °C · GFS · {time}', 'aurora.north': 'Aurora boreal', 'aurora.south': 'Aurora austral', 'aurora.probability': 'Probabilidade NOAA OVATION', 'air.title': 'Qualidade do ar', 'iss.title': 'Estação Espacial Internacional', 'iss.altitude': '{altitude} km de altitude',
      'eventDetail.open': 'VER FICHA COMPLETA', 'eventDetail.eyebrow': 'FICHA DA OCORRÊNCIA', 'eventDetail.category': 'CATEGORIA', 'eventDetail.indicator': 'INDICADOR', 'eventDetail.source': 'FONTE', 'eventDetail.published': 'PUBLICADO', 'eventDetail.coordinates': 'GPS (LATITUDE / LONGITUDE)', 'eventDetail.checked': 'CONSULTA DO MONITOR', 'eventDetail.reportedLocation': 'LOCAL INFORMADO PELA FONTE', 'eventDetail.nearRegion': 'REFERÊNCIA ADMINISTRATIVA PRÓXIMA', 'eventDetail.locating': 'LOCALIZANDO REFERÊNCIA…', 'eventDetail.noNearbyRegion': 'SEM REFERÊNCIA ADMINISTRATIVA PRÓXIMA', 'eventDetail.distanceApprox': 'CENTRO ADMINISTRATIVO A APROX. {distance} KM', 'eventDetail.openMap': 'ABRIR PONTO NO OPENSTREETMAP ↗', 'eventDetail.relatedEyebrow': 'CONTEXTO REGIONAL', 'eventDetail.relatedTitle': 'NOTÍCIAS RECENTES DO LOCAL', 'eventDetail.relatedNote': 'Referências jornalísticas no idioma selecionado, das últimas 24 horas e com correspondência clara ao local. Não constituem confirmação independente.', 'eventDetail.relatedLoading': 'VERIFICANDO COBERTURA LOCAL…', 'eventDetail.noRelated': 'Nenhuma notícia recente com correspondência local clara foi encontrada.', 'eventDetail.notice': 'Esta ficha reproduz dados da fonte indicada. Ela não substitui autoridades ou serviços de emergência.', 'eventDetail.openSource': 'ABRIR FONTE ORIGINAL ↗', 'eventDetail.share': 'COMPARTILHAR COM FONTE E HORÁRIO', 'eventDetail.copied': 'LINK E CONTEXTO COPIADOS.', 'eventDetail.shareFailed': 'NÃO FOI POSSÍVEL COMPARTILHAR NESTE NAVEGADOR.',
      'conflict.eyebrow': 'MONITORAMENTO JORNALÍSTICO', 'conflict.unverified': 'NÃO É CONFIRMAÇÃO MILITAR', 'conflict.scope': 'ÁREA MENCIONADA', 'conflict.reference': 'TIPO DE REFERÊNCIA', 'conflict.coordinates': 'COORDENADA DE REFERÊNCIA', 'conflict.latest': 'PUBLICAÇÃO MAIS RECENTE', 'conflict.referenceAdmin1': 'ESTADO / PROVÍNCIA', 'conflict.referenceCountry': 'PAÍS', 'conflict.mediaMetric': 'COBERTURA JORNALÍSTICA', 'conflict.notice': 'O ponto representa a região ou o país mencionado na manchete. Não indica local exato de ataque, lançamento ou impacto. Abra a fonte antes de interpretar o fato.', 'conflict.sourcesEyebrow': 'FONTES PUBLICADAS', 'conflict.sourcesTitle': 'MANCHETES RELACIONADAS', 'conflict.noArticles': 'Nenhuma manchete relacionada disponível neste idioma.',
      'notifications.active': 'ALERTAS LOCAIS ATIVOS', 'notifications.unsupported': 'ALERTAS NÃO SUPORTADOS NESTE NAVEGADOR', 'notifications.denied': 'ALERTAS NÃO AUTORIZADOS', 'alert.webgl': 'O globo 3D exige WebGL. Este navegador continuará no mapa 2D.', 'alert.locationDenied': 'Localização não autorizada pelo navegador.', 'alert.locationUnavailable': 'Geolocalização indisponível.'
    },
    en: {
      'meta.description': 'Public monitor of events, weather, seismic activity, auroras and global conditions in near real time.',
      'system.online': 'SYSTEM ONLINE', 'system.partial': 'PARTIAL DATA', 'system.offline': 'NO SOURCES', 'system.responding': 'SOURCES RESPONDING', 'system.syncing': 'SYNCING', 'system.sync': 'SYNC {time}',
      'theme.light': 'LIGHT MODE', 'theme.dark': 'DARK MODE',
      'nav.about': 'ABOUT', 'manifest.eyebrow': 'GLOBAL MONITOR / LIVE', 'manifest.line1': 'THE PLANET', 'manifest.line2': 'DOES NOT PAUSE.', 'manifest.description': 'Public events brought into one view, with verifiable source, time and location.',
      'risk.title': 'RISK FILTER', 'risk.highOnly': 'High priority only', 'layers.title': 'OPERATIONAL LAYERS', 'layers.temperature': 'Global temperature', 'layers.aurora': 'Northern and southern auroras', 'layers.air': 'Air quality', 'layers.regions': 'News by state / province', 'layers.conflicts': 'Conflicts in the press', 'layers.daylight': 'Day / night line', 'layers.satellite': 'Daily NASA satellite', 'layers.iss': 'ISS position',
      'sources.title': 'SOURCE INTEGRITY', 'sources.loading': 'Checking public sources…', 'sources.fail': 'FAILED', 'sources.ok': '{count} · OK', 'sources.snapshot15': 'Snapshot refreshed every 15 min', 'sources.activeOnly': 'Active alerts only', 'sources.grid15': '15° global grid', 'sources.newsCache': 'Public cache refreshed every 15 min', 'sources.conflictMedia': 'Journalistic monitoring refreshed every 15 min', 'sources.published': 'published', 'sources.checked': 'checked', 'sources.stale': 'DELAYED',
      'stage.eyebrow': 'ORBITAL VIEW / PUBLIC DATA', 'stage.visible': 'VISIBLE EVENTS', 'stage.locate': '⌖ NEAR ME', 'stage.regions': 'NEWS', 'stage.hideRegions': 'HIDE NEWS', 'stage.map2d': '2D MAP', 'stage.globe3d': '3D GLOBE', 'stage.refresh': '↻ REFRESH', 'stage.loading': 'INITIALIZING CARTOGRAPHY', 'stage.unavailable': 'CARTOGRAPHY UNAVAILABLE',
      'legend.critical': 'Critical', 'legend.high': 'High', 'legend.medium': 'Medium', 'legend.low': 'Low',
      'status.temperatureOff': 'TEMPERATURE: OFF', 'status.auroraOff': 'AURORA: OFF', 'status.airOff': 'AIR: OFF', 'status.regionsOff': 'REGIONAL NEWS: OFF', 'status.conflictsOff': 'CONFLICTS IN THE PRESS: OFF', 'status.satelliteOff': 'SATELLITE: OFF', 'status.issWaiting': 'ISS: WAITING',
      'spot.waiting': 'WAITING', 'spot.eyebrow': 'HIGHLIGHT', 'spot.consulting': 'CHECKING SOURCES', 'spot.initial': 'Real data will appear when sources respond.', 'spot.indicator': 'MAIN INDICATOR', 'spot.source': 'SOURCE', 'spot.updated': 'UPDATED', 'spot.coordinates': 'COORDINATES', 'spot.open': 'OPEN SOURCE ↗',
      'space.eyebrow': 'SPACE WEATHER / NOAA', 'space.title': "EARTH'S MAGNETISM", 'space.wind': 'SOLAR WIND', 'space.waiting': 'Waiting for NOAA SWPC.', 'feed.eyebrow': 'GLOBAL PULSE', 'feed.title': 'LATEST READINGS',
      'intel.eyebrow': 'REGIONAL INTELLIGENCE', 'intel.title': 'NEWS AND CAMERAS', 'intel.placeholder': 'State, province or country', 'intel.search': 'SEARCH', 'intel.initial': 'Select an event or search for a region.', 'intel.cameras': 'FIND EXTERNAL CAMERAS ON WINDY ↗', 'intel.notifications': 'ENABLE BROWSER ALERTS', 'intel.disclaimer': 'News is not independent confirmation. The camera button opens an external service; availability, proximity and freshness are not guaranteed.',
      'footer.monitor': 'INDEPENDENT MONITOR · PUBLIC DATA', 'footer.sync': 'LAST SYNC —',
      'about.eyebrow': 'ABOUT THIS MONITOR', 'about.title': 'Global information, with source and context.', 'about.lead': 'Seu Mundo Neste Momento brings public data about natural events, environmental conditions, space weather and human activity into a single view. Its purpose is to make information easier to access, not to cause fear or anticipate conclusions.',
      'about.realtimeTitle': 'What “near real time” means', 'about.realtime': 'Each institution publishes at a different pace. The ISS position may change within seconds; earthquakes, alerts, auroras, weather and satellite imagery may take minutes or hours. The displayed time belongs to the latest reading made available by the source — not necessarily the exact moment the event began.',
      'about.dataTitle': 'How data is handled', 'about.data': 'The panel shows source, time and location whenever they are available. The thermal layer represents 2-metre air temperature estimated by the NOAA GFS model; the colored surface is interpolated between model cells, not between thermometers. If a source fails, the system reports the outage or uses the latest snapshot clearly identified as a fallback. Missing values are never replaced by invented estimates.', 'about.limitsTitle': 'Important limitations',
      'about.limit1': 'This project does not replace public authorities, civil defense, weather services or emergency assistance.', 'about.limit2': 'News items are journalistic references, not independent confirmation.', 'about.limit3': 'Public cameras may be delayed, offline or not show the exact location.', 'about.limit4': 'Nuclear, radiological, biological or chemical alerts may appear only after publication by a previously accepted official source.', 'about.limit5': 'The monitor does not calculate weapon trajectories, predict impacts or assign responsibility without official confirmation.',
      'about.note': 'Independent project with no institutional affiliation to the consulted sources. Google Analytics is used only after consent to count visits and active users. External content may remain in its original language to preserve the published information.', 'about.signature': 'CONCEPT, VISUAL DIRECTION AND DEVELOPMENT',
      'consent.text': 'This site uses anonymous Google Analytics measurement to count visits and active users.', 'consent.allow': 'ALLOW', 'consent.reject': 'DECLINE',
      'cat.all': 'All', 'cat.earthquakes': 'Earthquakes', 'cat.wildfires': 'Wildfires', 'cat.storms': 'Storms', 'cat.volcanoes': 'Volcanoes', 'cat.floods': 'Floods', 'cat.other': 'Other', 'cat.hazmat': 'Biological / chemical', 'cat.nuclear': 'Nuclear / radiological',
      'risk.critical': 'CRITICAL LEVEL', 'risk.high': 'HIGH LEVEL', 'risk.medium': 'MEDIUM LEVEL', 'risk.low': 'LOW LEVEL',
      'event.quake': 'Earthquake {magnitude}', 'event.wildfire': 'Active wildfire', 'event.storm': 'Monitored storm', 'event.volcano': 'Volcanic activity', 'event.flood': 'Active flood', 'event.other': 'Natural event', 'event.gdacsWildfire': 'Wildfire monitored by GDACS', 'event.gdacsFlood': 'Flood monitored by GDACS', 'event.gdacsStorm': 'Monitored tropical cyclone', 'event.gdacsVolcano': 'Monitored volcanic activity', 'event.gdacsOther': 'Disaster monitored by GDACS', 'event.tsunami': 'Official tsunami alert', 'event.unknownLocation': 'Location not reported', 'event.quakeSummary': 'Seismic event published by USGS. Approximate depth: {depth} km.', 'event.eonetSummary': 'Open event monitored by NASA EONET.', 'event.active': 'ACTIVE', 'event.none': 'No events match the selected filters.',
      'kp.none': 'No storm', 'kp.minor': 'Minor', 'kp.moderate': 'Moderate', 'kp.strong': 'Strong', 'kp.severe': 'Severe', 'kp.extreme': 'Extreme', 'space.latest': "Latest reading: {time}. Negative Bz favors coupling with Earth's magnetic field.",
      'layer.tempLoading': 'TEMPERATURE: LOADING GLOBAL FIELD', 'layer.tempUnavailable': 'TEMPERATURE: GFS MODEL UNAVAILABLE', 'layer.tempNoReading': 'TEMPERATURE: NO READING', 'layer.tempPoints': 'TEMPERATURE: {count} POINTS · {min} TO {max} °C', 'layer.tempField': 'TEMPERATURE: NOAA GFS · {time} · {min} TO {max} °C', 'layer.auroraCells': 'AURORA: {count} NOAA CELLS', 'layer.airPoints': 'AIR: {count} POINTS · 15° GRID', 'layer.airUnavailable': 'AIR: SNAPSHOT UNAVAILABLE', 'layer.regionsLoading': 'NEWS: CHECKING REGIONAL COVERAGE', 'layer.regionsCount': 'NEWS: {count} COVERED STATES / PROVINCES', 'layer.regionsUnavailable': 'NEWS: REGIONAL BASE UNAVAILABLE', 'layer.regionSelected': 'NEWS: {name}', 'layer.conflictsLoading': 'CONFLICTS: CHECKING COVERAGE', 'layer.conflictsCount': 'CONFLICTS IN THE PRESS: {count} REFERENCES', 'layer.conflictsEmpty': 'CONFLICTS: NO REGIONAL REFERENCES IN THIS LANGUAGE', 'layer.satelliteOn': 'SATELLITE: NASA GIBS · {date} · DAILY',
      'iss.snapshot': 'ISS: FALLBACK SNAPSHOT', 'iss.unavailable': 'ISS: SOURCE UNAVAILABLE', 'weather.loading': 'Checking Open-Meteo…', 'weather.feels': 'Feels like', 'weather.humidity': 'Humidity', 'weather.wind': 'Wind', 'weather.unavailable': 'Weather unavailable: {error}',
      'news.loading': 'Checking public news…', 'news.coverage': 'Only news in the selected language, from the last 24 hours and with identifiable regional coverage. Cache refreshed every 15 minutes.', 'news.fallback': 'Insufficient regional coverage; showing the country.', 'news.none': 'No matching article was found in the recent cache for “{term}”.', 'news.source': 'News source', 'news.noTime': 'time not reported', 'news.error': 'The public news cache is temporarily unavailable.', 'news.google': 'Search Google News ↗', 'news.preview': 'NEWS PREVIEW', 'news.originalNotice': 'The headline and metadata below were published by the named source. The full article remains on the original website.', 'news.read': 'READ FULL ARTICLE ↗',
      'region.click': '{country} · click for news', 'region.metric': 'REGION', 'region.newsMetric': 'RECENT NEWS', 'temperature.approx': 'Approximate temperature', 'temperature.legend': '2 M AIR TEMPERATURE · GFS MODEL', 'temperature.readout': '{value} °C · GFS · {time}', 'aurora.north': 'Aurora borealis', 'aurora.south': 'Aurora australis', 'aurora.probability': 'NOAA OVATION probability', 'air.title': 'Air quality', 'iss.title': 'International Space Station', 'iss.altitude': '{altitude} km altitude',
      'eventDetail.open': 'VIEW FULL RECORD', 'eventDetail.eyebrow': 'EVENT RECORD', 'eventDetail.category': 'CATEGORY', 'eventDetail.indicator': 'INDICATOR', 'eventDetail.source': 'SOURCE', 'eventDetail.published': 'PUBLISHED', 'eventDetail.coordinates': 'GPS (LATITUDE / LONGITUDE)', 'eventDetail.checked': 'MONITOR CHECK', 'eventDetail.reportedLocation': 'LOCATION REPORTED BY THE SOURCE', 'eventDetail.nearRegion': 'NEAREST ADMINISTRATIVE REFERENCE', 'eventDetail.locating': 'LOCATING REFERENCE…', 'eventDetail.noNearbyRegion': 'NO NEARBY ADMINISTRATIVE REFERENCE', 'eventDetail.distanceApprox': 'ADMINISTRATIVE CENTRE APPROX. {distance} KM AWAY', 'eventDetail.openMap': 'OPEN POINT IN OPENSTREETMAP ↗', 'eventDetail.relatedEyebrow': 'REGIONAL CONTEXT', 'eventDetail.relatedTitle': 'RECENT LOCAL NEWS', 'eventDetail.relatedNote': 'Journalistic references in the selected language, from the last 24 hours and with a clear match to the location. They are not independent confirmation.', 'eventDetail.relatedLoading': 'CHECKING LOCAL COVERAGE…', 'eventDetail.noRelated': 'No recent article with a clear local match was found.', 'eventDetail.notice': 'This record reproduces data from the named source. It does not replace authorities or emergency services.', 'eventDetail.openSource': 'OPEN ORIGINAL SOURCE ↗', 'eventDetail.share': 'SHARE WITH SOURCE AND TIME', 'eventDetail.copied': 'LINK AND CONTEXT COPIED.', 'eventDetail.shareFailed': 'SHARING IS NOT AVAILABLE IN THIS BROWSER.',
      'conflict.eyebrow': 'JOURNALISTIC MONITORING', 'conflict.unverified': 'NOT MILITARY CONFIRMATION', 'conflict.scope': 'MENTIONED AREA', 'conflict.reference': 'REFERENCE TYPE', 'conflict.coordinates': 'REFERENCE COORDINATE', 'conflict.latest': 'LATEST PUBLICATION', 'conflict.referenceAdmin1': 'STATE / PROVINCE', 'conflict.referenceCountry': 'COUNTRY', 'conflict.mediaMetric': 'JOURNALISTIC COVERAGE', 'conflict.notice': 'The point represents the region or country mentioned in the headline. It does not indicate an exact attack, launch or impact location. Open the source before interpreting the report.', 'conflict.sourcesEyebrow': 'PUBLISHED SOURCES', 'conflict.sourcesTitle': 'RELATED HEADLINES', 'conflict.noArticles': 'No related headline is available in this language.',
      'notifications.active': 'LOCAL ALERTS ACTIVE', 'notifications.unsupported': 'ALERTS NOT SUPPORTED BY THIS BROWSER', 'notifications.denied': 'ALERTS NOT AUTHORIZED', 'alert.webgl': 'The 3D globe requires WebGL. This browser will remain on the 2D map.', 'alert.locationDenied': 'Location permission was not granted.', 'alert.locationUnavailable': 'Geolocation is unavailable.'
    },
    es: {
      'meta.description': 'Monitor público de acontecimientos, clima, actividad sísmica, auroras y condiciones globales en tiempo casi real.',
      'system.online': 'SISTEMA EN LÍNEA', 'system.partial': 'DATOS PARCIALES', 'system.offline': 'SIN FUENTES', 'system.responding': 'FUENTES RESPONDIENDO', 'system.syncing': 'SINCRONIZANDO', 'system.sync': 'SINCRONIZACIÓN {time}',
      'theme.light': 'MODO CLARO', 'theme.dark': 'MODO OSCURO',
      'nav.about': 'ACERCA DE', 'manifest.eyebrow': 'MONITOR GLOBAL / EN VIVO', 'manifest.line1': 'EL PLANETA', 'manifest.line2': 'NO SE DETIENE.', 'manifest.description': 'Acontecimientos públicos reunidos en una sola vista, con fuente, hora y ubicación verificables.',
      'risk.title': 'FILTRO DE RIESGO', 'risk.highOnly': 'Solo alta prioridad', 'layers.title': 'CAPAS OPERATIVAS', 'layers.temperature': 'Temperatura global', 'layers.aurora': 'Auroras del norte y del sur', 'layers.air': 'Calidad del aire', 'layers.regions': 'Noticias por estado / provincia', 'layers.conflicts': 'Conflictos en la prensa', 'layers.daylight': 'Línea día / noche', 'layers.satellite': 'Satélite NASA diario', 'layers.iss': 'Posición de la ISS',
      'sources.title': 'INTEGRIDAD DE LAS FUENTES', 'sources.loading': 'Consultando fuentes públicas…', 'sources.fail': 'FALLA', 'sources.ok': '{count} · OK', 'sources.snapshot15': 'Instantánea renovada cada 15 min', 'sources.activeOnly': 'Solo alertas activas', 'sources.grid15': 'Cuadrícula global de 15°', 'sources.newsCache': 'Caché pública renovada cada 15 min', 'sources.conflictMedia': 'Monitoreo periodístico renovado cada 15 min', 'sources.published': 'publicado', 'sources.checked': 'consultado', 'sources.stale': 'RETRASADO',
      'stage.eyebrow': 'VISIÓN ORBITAL / DATOS PÚBLICOS', 'stage.visible': 'EVENTOS VISIBLES', 'stage.locate': '⌖ CERCA DE MÍ', 'stage.regions': 'NOTICIAS', 'stage.hideRegions': 'OCULTAR NOTICIAS', 'stage.map2d': 'MAPA 2D', 'stage.globe3d': 'GLOBO 3D', 'stage.refresh': '↻ ACTUALIZAR', 'stage.loading': 'INICIANDO CARTOGRAFÍA', 'stage.unavailable': 'CARTOGRAFÍA NO DISPONIBLE',
      'legend.critical': 'Crítico', 'legend.high': 'Alto', 'legend.medium': 'Medio', 'legend.low': 'Bajo',
      'status.temperatureOff': 'TEMPERATURA: DESACTIVADA', 'status.auroraOff': 'AURORA: DESACTIVADA', 'status.airOff': 'AIRE: DESACTIVADO', 'status.regionsOff': 'NOTICIAS REGIONALES: DESACTIVADAS', 'status.conflictsOff': 'CONFLICTOS EN LA PRENSA: DESACTIVADOS', 'status.satelliteOff': 'SATÉLITE: DESACTIVADO', 'status.issWaiting': 'ISS: ESPERANDO',
      'spot.waiting': 'ESPERANDO', 'spot.eyebrow': 'DESTACADO', 'spot.consulting': 'CONSULTANDO FUENTES', 'spot.initial': 'Los datos reales aparecerán cuando respondan las fuentes.', 'spot.indicator': 'INDICADOR PRINCIPAL', 'spot.source': 'FUENTE', 'spot.updated': 'ACTUALIZACIÓN', 'spot.coordinates': 'COORDENADAS', 'spot.open': 'ABRIR FUENTE ↗',
      'space.eyebrow': 'CLIMA ESPACIAL / NOAA', 'space.title': 'MAGNETISMO DE LA TIERRA', 'space.wind': 'VIENTO SOLAR', 'space.waiting': 'Esperando NOAA SWPC.', 'feed.eyebrow': 'PULSO GLOBAL', 'feed.title': 'ÚLTIMAS LECTURAS',
      'intel.eyebrow': 'INTELIGENCIA REGIONAL', 'intel.title': 'NOTICIAS Y CÁMARAS', 'intel.placeholder': 'Estado, provincia o país', 'intel.search': 'BUSCAR', 'intel.initial': 'Seleccione un evento o busque una región.', 'intel.cameras': 'BUSCAR CÁMARAS EXTERNAS EN WINDY ↗', 'intel.notifications': 'ACTIVAR ALERTAS DEL NAVEGADOR', 'intel.disclaimer': 'Las noticias no son confirmación independiente. El botón de cámaras abre un servicio externo; no se garantizan disponibilidad, proximidad ni actualización.',
      'footer.monitor': 'MONITOR INDEPENDIENTE · DATOS PÚBLICOS', 'footer.sync': 'ÚLTIMA SINCRONIZACIÓN —',
      'about.eyebrow': 'ACERCA DE ESTE MONITOR', 'about.title': 'Información global, con fuente y contexto.', 'about.lead': 'Seu Mundo Neste Momento reúne datos públicos sobre acontecimientos naturales, condiciones ambientales, clima espacial y actividad humana en una sola visualización. El objetivo es facilitar el acceso a la información, no provocar miedo ni anticipar conclusiones.',
      'about.realtimeTitle': 'Qué significa “tiempo casi real”', 'about.realtime': 'Cada institución publica a un ritmo diferente. La posición de la ISS puede cambiar en segundos; terremotos, alertas, auroras, clima e imágenes satelitales pueden tardar minutos u horas. La hora mostrada pertenece a la lectura más reciente publicada por la fuente, no necesariamente al momento exacto en que comenzó el hecho.',
      'about.dataTitle': 'Cómo se tratan los datos', 'about.data': 'El panel informa la fuente, la hora y la ubicación siempre que estén disponibles. La capa térmica representa la temperatura del aire a 2 metros estimada por el modelo NOAA GFS; la superficie coloreada se interpola entre celdas del modelo, no entre termómetros. Si una fuente falla, el sistema indica la indisponibilidad o utiliza la última instantánea identificada como contingencia. Los valores ausentes nunca se sustituyen por estimaciones inventadas.', 'about.limitsTitle': 'Límites importantes',
      'about.limit1': 'Este proyecto no sustituye a las autoridades, la defensa civil, los servicios meteorológicos ni la atención de emergencias.', 'about.limit2': 'Las noticias son referencias periodísticas, no confirmación independiente.', 'about.limit3': 'Las cámaras públicas pueden tener retraso, estar fuera de línea o no mostrar el lugar exacto.', 'about.limit4': 'Las alertas nucleares, radiológicas, biológicas o químicas solo pueden aparecer después de una publicación de una fuente oficial previamente aceptada.', 'about.limit5': 'El monitor no calcula trayectorias de armamentos, no predice impactos ni atribuye responsabilidades sin confirmación oficial.',
      'about.note': 'Proyecto independiente, sin vínculo institucional con las fuentes consultadas. Google Analytics se utiliza solo con consentimiento para contar visitas y usuarios activos. El contenido externo puede permanecer en su idioma original para preservar la información publicada.', 'about.signature': 'CONCEPTO, DIRECCIÓN VISUAL Y DESARROLLO',
      'consent.text': 'Este sitio utiliza medición anónima de Google Analytics para contar visitas y usuarios activos.', 'consent.allow': 'PERMITIR', 'consent.reject': 'RECHAZAR',
      'cat.all': 'Todos', 'cat.earthquakes': 'Terremotos', 'cat.wildfires': 'Incendios', 'cat.storms': 'Tormentas', 'cat.volcanoes': 'Volcanes', 'cat.floods': 'Inundaciones', 'cat.other': 'Otros', 'cat.hazmat': 'Biológico / químico', 'cat.nuclear': 'Nuclear / radiológico',
      'risk.critical': 'NIVEL CRÍTICO', 'risk.high': 'NIVEL ALTO', 'risk.medium': 'NIVEL MEDIO', 'risk.low': 'NIVEL BAJO',
      'event.quake': 'Terremoto {magnitude}', 'event.wildfire': 'Incendio activo', 'event.storm': 'Tormenta monitoreada', 'event.volcano': 'Actividad volcánica', 'event.flood': 'Inundación activa', 'event.other': 'Evento natural', 'event.gdacsWildfire': 'Incendio monitoreado por GDACS', 'event.gdacsFlood': 'Inundación monitoreada por GDACS', 'event.gdacsStorm': 'Ciclón tropical monitoreado', 'event.gdacsVolcano': 'Actividad volcánica monitoreada', 'event.gdacsOther': 'Desastre monitoreado por GDACS', 'event.tsunami': 'Alerta oficial de tsunami', 'event.unknownLocation': 'Ubicación no informada', 'event.quakeSummary': 'Evento sísmico publicado por USGS. Profundidad aproximada de {depth} km.', 'event.eonetSummary': 'Evento abierto monitoreado por NASA EONET.', 'event.active': 'ACTIVO', 'event.none': 'Ningún evento coincide con los filtros.',
      'kp.none': 'Sin tormenta', 'kp.minor': 'Menor', 'kp.moderate': 'Moderada', 'kp.strong': 'Fuerte', 'kp.severe': 'Severa', 'kp.extreme': 'Extrema', 'space.latest': 'Lectura más reciente: {time}. Un Bz negativo favorece el acoplamiento con el campo magnético terrestre.',
      'layer.tempLoading': 'TEMPERATURA: CARGANDO CAMPO GLOBAL', 'layer.tempUnavailable': 'TEMPERATURA: MODELO GFS NO DISPONIBLE', 'layer.tempNoReading': 'TEMPERATURA: SIN LECTURA', 'layer.tempPoints': 'TEMPERATURA: {count} PUNTOS · {min} A {max} °C', 'layer.tempField': 'TEMPERATURA: NOAA GFS · {time} · {min} A {max} °C', 'layer.auroraCells': 'AURORA: {count} CELDAS NOAA', 'layer.airPoints': 'AIRE: {count} PUNTOS · CUADRÍCULA 15°', 'layer.airUnavailable': 'AIRE: INSTANTÁNEA NO DISPONIBLE', 'layer.regionsLoading': 'NOTICIAS: COMPROBANDO COBERTURA REGIONAL', 'layer.regionsCount': 'NOTICIAS: {count} ESTADOS / PROVINCIAS CUBIERTOS', 'layer.regionsUnavailable': 'NOTICIAS: BASE REGIONAL NO DISPONIBLE', 'layer.regionSelected': 'NOTICIAS: {name}', 'layer.conflictsLoading': 'CONFLICTOS: COMPROBANDO COBERTURA', 'layer.conflictsCount': 'CONFLICTOS EN LA PRENSA: {count} REFERENCIAS', 'layer.conflictsEmpty': 'CONFLICTOS: SIN REFERENCIAS REGIONALES EN ESTE IDIOMA', 'layer.satelliteOn': 'SATÉLITE: NASA GIBS · {date} · DIARIO',
      'iss.snapshot': 'ISS: INSTANTÁNEA DE CONTINGENCIA', 'iss.unavailable': 'ISS: FUENTE NO DISPONIBLE', 'weather.loading': 'Consultando Open-Meteo…', 'weather.feels': 'Sensación', 'weather.humidity': 'Humedad', 'weather.wind': 'Viento', 'weather.unavailable': 'Clima no disponible: {error}',
      'news.loading': 'Consultando noticias públicas…', 'news.coverage': 'Solo noticias en el idioma seleccionado, de las últimas 24 horas y con cobertura regional identificable. Caché renovada cada 15 minutos.', 'news.fallback': 'Cobertura regional insuficiente; mostrando el país.', 'news.none': 'No se encontró ninguna noticia coincidente en la caché reciente para “{term}”.', 'news.source': 'Fuente periodística', 'news.noTime': 'hora no informada', 'news.error': 'La caché pública de noticias no está disponible temporalmente.', 'news.google': 'Buscar en Google Noticias ↗', 'news.preview': 'VISTA PREVIA DE LA NOTICIA', 'news.originalNotice': 'El titular y los metadatos fueron publicados por la fuente indicada. El artículo completo permanece en el sitio original.', 'news.read': 'LEER NOTICIA COMPLETA ↗',
      'region.click': '{country} · clic para noticias', 'region.metric': 'REGIÓN', 'region.newsMetric': 'NOTICIA RECIENTE', 'temperature.approx': 'Temperatura aproximada', 'temperature.legend': 'TEMPERATURA DEL AIRE A 2 M · MODELO GFS', 'temperature.readout': '{value} °C · GFS · {time}', 'aurora.north': 'Aurora boreal', 'aurora.south': 'Aurora austral', 'aurora.probability': 'Probabilidad NOAA OVATION', 'air.title': 'Calidad del aire', 'iss.title': 'Estación Espacial Internacional', 'iss.altitude': '{altitude} km de altitud',
      'eventDetail.open': 'VER FICHA COMPLETA', 'eventDetail.eyebrow': 'FICHA DEL EVENTO', 'eventDetail.category': 'CATEGORÍA', 'eventDetail.indicator': 'INDICADOR', 'eventDetail.source': 'FUENTE', 'eventDetail.published': 'PUBLICADO', 'eventDetail.coordinates': 'GPS (LATITUD / LONGITUD)', 'eventDetail.checked': 'CONSULTA DEL MONITOR', 'eventDetail.reportedLocation': 'LUGAR INFORMADO POR LA FUENTE', 'eventDetail.nearRegion': 'REFERENCIA ADMINISTRATIVA MÁS CERCANA', 'eventDetail.locating': 'LOCALIZANDO REFERENCIA…', 'eventDetail.noNearbyRegion': 'SIN REFERENCIA ADMINISTRATIVA CERCANA', 'eventDetail.distanceApprox': 'CENTRO ADMINISTRATIVO A APROX. {distance} KM', 'eventDetail.openMap': 'ABRIR PUNTO EN OPENSTREETMAP ↗', 'eventDetail.relatedEyebrow': 'CONTEXTO REGIONAL', 'eventDetail.relatedTitle': 'NOTICIAS RECIENTES DEL LUGAR', 'eventDetail.relatedNote': 'Referencias periodísticas en el idioma seleccionado, de las últimas 24 horas y con coincidencia clara con el lugar. No constituyen confirmación independiente.', 'eventDetail.relatedLoading': 'COMPROBANDO COBERTURA LOCAL…', 'eventDetail.noRelated': 'No se encontró ninguna noticia reciente con coincidencia local clara.', 'eventDetail.notice': 'Esta ficha reproduce datos de la fuente indicada. No sustituye a las autoridades ni a los servicios de emergencia.', 'eventDetail.openSource': 'ABRIR FUENTE ORIGINAL ↗', 'eventDetail.share': 'COMPARTIR CON FUENTE Y HORA', 'eventDetail.copied': 'ENLACE Y CONTEXTO COPIADOS.', 'eventDetail.shareFailed': 'NO SE PUDO COMPARTIR EN ESTE NAVEGADOR.',
      'conflict.eyebrow': 'MONITOREO PERIODÍSTICO', 'conflict.unverified': 'NO ES CONFIRMACIÓN MILITAR', 'conflict.scope': 'ÁREA MENCIONADA', 'conflict.reference': 'TIPO DE REFERENCIA', 'conflict.coordinates': 'COORDENADA DE REFERENCIA', 'conflict.latest': 'PUBLICACIÓN MÁS RECIENTE', 'conflict.referenceAdmin1': 'ESTADO / PROVINCIA', 'conflict.referenceCountry': 'PAÍS', 'conflict.mediaMetric': 'COBERTURA PERIODÍSTICA', 'conflict.notice': 'El punto representa la región o el país mencionado en el titular. No indica un lugar exacto de ataque, lanzamiento o impacto. Abra la fuente antes de interpretar la información.', 'conflict.sourcesEyebrow': 'FUENTES PUBLICADAS', 'conflict.sourcesTitle': 'TITULARES RELACIONADOS', 'conflict.noArticles': 'No hay ningún titular relacionado disponible en este idioma.',
      'notifications.active': 'ALERTAS LOCALES ACTIVAS', 'notifications.unsupported': 'ALERTAS NO COMPATIBLES CON ESTE NAVEGADOR', 'notifications.denied': 'ALERTAS NO AUTORIZADAS', 'alert.webgl': 'El globo 3D requiere WebGL. Este navegador permanecerá en el mapa 2D.', 'alert.locationDenied': 'No se autorizó el acceso a la ubicación.', 'alert.locationUnavailable': 'La geolocalización no está disponible.'
    }
  };

  const supported = ['pt-BR', 'en', 'es'];
  let current;
  try { current = localStorage.getItem('site-language'); } catch {}
  if (!supported.includes(current)) {
    const browserLanguage = (navigator.language || 'pt-BR').toLowerCase();
    current = browserLanguage.startsWith('es') ? 'es' : browserLanguage.startsWith('en') ? 'en' : 'pt-BR';
  }
  const translate = (key, variables = {}) => {
    const template = translations[current]?.[key] ?? translations['pt-BR'][key] ?? key;
    return String(template).replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? `{${name}}`);
  };
  const apply = (root = document) => {
    document.documentElement.lang = current;
    document.title = 'Seu Mundo Neste Momento';
    const description = document.querySelector('meta[name="description"]');
    if (description) description.content = translate('meta.description');
    root.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = translate(element.dataset.i18n); });
    root.querySelectorAll('[data-i18n-placeholder]').forEach(element => { element.placeholder = translate(element.dataset.i18nPlaceholder); });
    const selector = document.getElementById('language-select'); if (selector) selector.value = current;
  };
  const set = language => {
    if (!supported.includes(language)) return;
    current = language;
    try { localStorage.setItem('site-language', language); } catch {}
    apply();
    window.dispatchEvent(new CustomEvent('languagechange', { detail: { language } }));
  };
  window.i18n = { t: translate, apply, set, get language() { return current; }, locale: () => current === 'pt-BR' ? 'pt-BR' : current === 'es' ? 'es-ES' : 'en-US' };
  apply();
})();
