import {mkdir,writeFile} from 'node:fs/promises';
const get=async url=>{const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'SeuMundoMonitor/2.0 GitHub Actions'}});if(!r.ok)throw new Error(`${url} HTTP ${r.status}`);return r.json()};
const qRisk=m=>m>=6.5?'critical':m>=5.5?'high':m>=4.5?'medium':'low';
const cat=s=>{s=(s||'').toLowerCase();if(s.includes('wildfire'))return'wildfires';if(s.includes('storm')||s.includes('cyclone')||s.includes('severe'))return'storms';if(s.includes('volcano'))return'volcanoes';if(s.includes('flood'))return'floods';return'other'};
const last=t=>{if(!Array.isArray(t)||!t.length)return null;if(t[0]&&typeof t[0]==='object'&&!Array.isArray(t[0]))return t.reduce((a,b)=>!a||new Date(b.time_tag||0)>new Date(a.time_tag||0)?b:a,null);return t.length>1&&Array.isArray(t[0])?Object.fromEntries(t[0].map((h,i)=>[h,t.at(-1)[i]])):null};
const [q,e,iss,kp,mag,plasma,aurora]=await Promise.allSettled([
  get('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson'),get('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=250'),get('https://api.wheretheiss.at/v1/satellites/25544'),get('https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json'),get('https://services.swpc.noaa.gov/json/rtsw/rtsw_mag_1m.json'),get('https://services.swpc.noaa.gov/json/rtsw/rtsw_wind_1m.json'),get('https://services.swpc.noaa.gov/json/ovation_aurora_latest.json')]);
const events=[];
if(q.status==='fulfilled')events.push(...(q.value.features||[]).map(f=>({id:`usgs-${f.id}`,category:'earthquakes',severity:qRisk(Number(f.properties.mag)||0),title:`Terremoto ${(Number(f.properties.mag)||0).toFixed(1)}`,location:f.properties.place||'Local não informado',summary:`Evento sísmico publicado pelo USGS. Profundidade aproximada de ${Number(f.geometry.coordinates[2]).toFixed(1)} km.`,metric:`M ${(Number(f.properties.mag)||0).toFixed(1)}`,timestamp:new Date(f.properties.time).toISOString(),source:'USGS',lat:f.geometry.coordinates[1],lon:f.geometry.coordinates[0],url:f.properties.url})));
if(e.status==='fulfilled')events.push(...(e.value.events||[]).flatMap(x=>{const g=x.geometry?.at(-1);if(!g||g.type!=='Point')return[];const category=cat(x.categories?.[0]?.title);if(category==='earthquakes')return[];return[{id:`eonet-${x.id}`,category,severity:['volcanoes','storms'].includes(category)?'high':['wildfires','floods'].includes(category)?'medium':'low',title:{wildfires:'Incêndio ativo',storms:'Tempestade monitorada',volcanoes:'Atividade vulcânica',floods:'Inundação ativa',other:'Evento natural'}[category],location:x.title,summary:x.description||'Evento aberto acompanhado pelo NASA EONET.',metric:g.magnitudeValue?`${g.magnitudeValue} ${g.magnitudeUnit||''}`:'ATIVO',timestamp:g.date,source:'NASA EONET',lat:g.coordinates[1],lon:g.coordinates[0],url:x.sources?.[0]?.url||x.link}]}));
const kr=kp.status==='fulfilled'?last(kp.value):null,mr=mag.status==='fulfilled'?last(mag.value):null,pr=plasma.status==='fulfilled'?last(plasma.value):null;
const snapshot={generatedAt:new Date().toISOString(),events:events.sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)),iss:iss.status==='fulfilled'?{lat:iss.value.latitude,lon:iss.value.longitude,altitude:iss.value.altitude,velocity:iss.value.velocity,timestamp:new Date(iss.value.timestamp*1000).toISOString()}:null,space:{kp:Number(kr?.Kp??kr?.kp)||null,bz:Number(mr?.bz_gsm??mr?.bz)||null,wind:Number(pr?.proton_speed??pr?.speed)||null,time:kr?.time_tag||mr?.time_tag||pr?.time_tag||new Date().toISOString()},aurora:aurora.status==='fulfilled'?(aurora.value.coordinates||[]).flatMap(p=>{const rawLon=Number(p[0]),lat=Number(p[1]),intensity=Number(p[2]);if(!Number.isFinite(rawLon)||!Number.isFinite(lat)||intensity<3)return[];const lon=rawLon>180?rawLon-360:rawLon;return Math.abs(Math.round(lat))%2||Math.abs(Math.round(lon))%2?[]:[{lat,lon,intensity}]}):[],sources:{usgs:q.status,eonet:e.status,iss:iss.status,noaa:kp.status,ovation:aurora.status}};
await mkdir('data',{recursive:true});await writeFile('data/snapshot.json',JSON.stringify(snapshot));
console.log(`snapshot: ${snapshot.events.length} events, ${snapshot.aurora.length} aurora cells`);
